mame_executable: c:\Programs\LaunchBox\Emulators\MAME 0.278\mame.exe
softlist_rom_sources_dir: c:\Programs\LaunchBox\Emulators\MAME 0.278\roms\softlist
out_romset_dir: c:\temp\mame_curated_romset_0.278
mess_ini_path: c:\Programs\LaunchBox\Emulators\MAME 0.278\folders\mess.ini
system_softlist_yaml_file: system_softlist.yml
mess_xml_file: mess.xml
