mame_executable: c:\Programs\LaunchBox\Emulators\MAME 0.278\mame.exe
softlist_rom_sources_dir: c:\Programs\LaunchBox\Emulators\MAME 0.278\roms\softlist
out_romset_dir: r:\roms\other\mame-mess
mess_ini_path: c:\Programs\LaunchBox\Emulators\MAME 0.278\folders\mess.ini
system_softlist_yaml_file: C:\Users\Gary\Documents\Github-dsync89\mess-curator\system_softlist.yml
mess_version: '278'
mess_xml_file: ''
